// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const listFoo = `-- name: ListFoo :iter
SELECT bar FROM foo
`

func (q *Queries) ListFoo(ctx context.Context, db DBTX, iter func(bar sql.NullInt32) error) error {
	rows, err := db.QueryContext(ctx, listFoo)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var bar sql.NullInt32
		if err := rows.Scan(&bar); err != nil {
			return err
		}
		err = iter(bar)
		if err != nil {
			return err
		}
	}
	if err := rows.Close(); err != nil {
		return err
	}
	if err := rows.Err(); err != nil {
		return err
	}
	return nil
}
