// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package querytest

import (
	"database/sql"
)

type Baz struct {
	One sql.NullInt32
	Two sql.NullInt32
}

type Foo struct {
	Bar bool
}
